server:
  port: 8080

spring:
  application:
    name: user-ms
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
    show-sql: true
  profiles:
    active: prod
app:
  default-quote-task: 10
  jwt-secret-key: "5evwaFf/JMT6G4uAhHK8BZREcLQ="
  jwt-issuer: com.ballnet.user
  jwt-expire-in-seconds: 86400
logging:
  level:
    com.ballnet.user.service: debug
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org.hibernate.type.descriptor.sql: trace
management:
  endpoints:
    web:
      exposure:
        include=*:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    path: /swagger-ui.html
kafka:
  bootstrapAddress: http://localhost:9092
  topic:
    registration:
      partition: 8
      replication: 1